


#声明注册地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


    register-with-eureka: true
#开启注册功能
spring:
  application:
    name: user
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3000/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
  redis:
    port: 6379
    host: localhost
    password:
  sleuth:
    enabled: true
    sampler:
      rate: 10
      probability: 0.1
  zipkin:
    enabled: true
#    base-url: http://localhost:9411
    sender:
      type: rabbit
    rabbitmq:
      addresses: 60.205.212.112

  rabbitmq:
    password: guest
    username: guest
    port: 5672
    addresses: 60.205.212.112
#  cloud:
#    stream:
#      bindings:
#        input2:
#          destination: input2
#        input1:
#          destination: input1




#  cloud:
#    stream:
#      bindings:
#        input:
#          destination: queue.log.messages
#          binder: myrabbit
#          group: logMessage
#        output:
#          destination: queue.log.messages
#          binder: myrabbit
#      binders:
#        myrabbit:
#          type: rabbit





order:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule




#pagehelper配置
pagehelper:
  reasonable: true  #分页参数合理化
  support-methods-arguments: true  #自动根据params配置获取分页参数
  params: count=countsql




#log配置
logging:
  level:
    com:
      example:
        user:
          dao: debug

mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml


feign:
  hystrix:
    enabled: false


#开启sleuth链路追踪功能



