






spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3000/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sleuth:
    sampler:
      rate: 1000
      probability: 1.0
    enabled: true


    zipkin:
      enabled: true
#      base-url: http://localhost:9411
      sender:
        type: rabbit
    rabbitmq:
        addresses: 60.205.212.112

  rabbitmq:
    password: guest
    username: guest
    port: 5672
    addresses: 60.205.212.112
#  cloud:
#    stream:
#      bindings:
#        testMessage:
#          group: order
#          content-type: application/json

pagehelper:
  reasonable: true  #分页参数合理化
  support-methods-arguments: true
  params: count=countsql


eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka






feign:
  hystrix:
    enabled: false

